Repository jenkinsci/google-oauth-plugin, pull requests merged in 2023-10, with the labels that each got.

#186 Enable creating multiple Google credentials for the same project id
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/RemotableGoogleCredentials.java
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials/config.jelly
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials/config.jelly
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentialsTest.java
  src/test/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentialsTest/testMigration/credentials.xml
Labels: enhancement

#195 Add scope to credentials
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/RemotableGoogleCredentials.java
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials/config.jelly
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials/config.jelly
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentialsTest.java
Labels: enhancement

#189 Removed 1 unnecessary stubbing in GoogleRobotPrivateKeyCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentialsTest.java
Labels: tests

#190 Removed 2 unnecessary stubbings in JsonServiceAccountConfigTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/JsonServiceAccountConfigTest.java
Labels: tests

#170 Apply upcoming core styling to file upload
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/P12ServiceAccountConfig/config.jelly
Labels: maintenance, ui

#199 Enable CD Permissions on google-oauth-plugin
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: developer
