Repository jenkinsci/google-oauth-plugin, pull requests merged in 2023-12, with the labels that each got.

#208 Adding a validation for the required email field in p12 credentials form
  src/main/java/com/google/jenkins/plugins/credentials/oauth/P12ServiceAccountConfig.java
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/Messages.properties
Labels: enhancement

#206 Use Guava from Jenkins core
  pom.xml
Labels: maintenance

#201 allow manual setting of credential IDs and descriptions
  src/main/java/com/google/jenkins/plugins/credentials/oauth/AbstractGoogleRobotCredentialsDescriptor.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials.java
  src/main/java/com/google/jenkins/plugins/credentials/oauth/RemotableGoogleCredentials.java
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentials/config.jelly
  src/main/resources/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials/config.jelly
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotMetadataCredentialsTest.java
  src/test/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentialsTest.java
Labels: enhancement

#214 add constructor for backward compatibility
  src/main/java/com/google/jenkins/plugins/credentials/oauth/GoogleRobotPrivateKeyCredentials.java
Labels: bug

#217 Require Jenkins 2.401.3 or newer
  pom.xml
Labels: developer
